import { StyleSheet } from 'react-native';
import { borderRadius, spacing, typography, colors } from '../../../styles/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#04070F',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
    zIndex: 12,
  },
  headerButton: {
    width: 44,
    height: 44,
    borderRadius: borderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: spacing.md,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  headerHidden: {
    opacity: 0,
  },
  headerEyebrow: {
    color: 'rgba(255,255,255,0.46)',
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.semibold as any,
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold as any,
  },
  headerSubtitle: {
    color: 'rgba(221,234,254,0.74)',
    fontSize: typography.fontSize.xs,
    marginTop: 2,
  },
  saveButton: {
    minWidth: 78,
    height: 44,
    borderRadius: borderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2563EB',
    paddingHorizontal: spacing.md,
  },
  saveButtonDisabled: {
    opacity: 0.55,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.bold as any,
  },
  editorStage: {
    flex: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: 92,
  },
  stageShell: {
    flex: 1,
    borderRadius: 34,
    backgroundColor: 'rgba(7,12,22,0.46)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
    padding: 6,
  },
  canvas: {
    flex: 1,
    borderRadius: 28,
    overflow: 'hidden',
    backgroundColor: '#0E162A',
  },
  canvasImage: {
    width: '100%',
    height: '100%',
  },
  lookToast: {
    position: 'absolute',
    left: spacing.xl,
    right: spacing.xl,
    bottom: 78,
    alignItems: 'center',
    zIndex: 16,
  },
  lookToastText: {
    color: '#FFFFFF',
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold as any,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    borderRadius: borderRadius.full,
    backgroundColor: 'rgba(6,10,20,0.42)',
    overflow: 'hidden',
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
  },
  vignetteTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '28%',
  },
  vignetteBottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: '30%',
  },
  vignetteLeft: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: '24%',
  },
  vignetteRight: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: '24%',
  },
  dimLayer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#000000',
  },
  gradeSwipeZone: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 12,
  },
  stageTopOverlay: {
    position: 'absolute',
    top: spacing.md,
    left: spacing.md,
    right: spacing.md,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  stagePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: borderRadius.full,
    backgroundColor: 'rgba(5, 10, 20, 0.56)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  stagePillText: {
    color: '#FFFFFF',
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.semibold as any,
  },
  layerWrap: {
    position: 'absolute',
  },
  layerSurface: {
    minWidth: 56,
    minHeight: 36,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'visible',
  },
  textBackdropWrap: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'visible',
  },
  textBackdropSwash: {
    position: 'absolute',
    borderWidth: 0,
  },
  textBackdropSwashMain: {
    top: -2,
    borderWidth: 1,
    left: -6,
    right: -4,
    bottom: -1,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 32,
    transform: [{ rotate: '-1.5deg' }],
  },
  textBackdropSwashAccent: {
    top: 6,
    bottom: 6,
    left: 8,
    right: 14,
    borderRadius: 22,
    opacity: 0.52,
    transform: [{ rotate: '1.4deg' }],
  },
  textBackdropSwashTail: {
    top: 4,
    borderWidth: 1,
    bottom: 4,
    left: -10,
    width: 42,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 12,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 18,
    opacity: 0.94,
    transform: [{ rotate: '-4deg' }],
  },
  layerSurfaceSelected: {
    backgroundColor: 'rgba(9, 17, 31, 0.18)',
  },
  layerText: {
    fontWeight: '900',
    textShadowColor: 'rgba(0,0,0,0.52)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 14,
  },
  layerStrokeText: {
    position: 'absolute',
    top: 8,
    left: 12,
    right: 12,
    bottom: 8,
    fontWeight: '900',
  },
  selectionOutline: {
    position: 'absolute',
    top: -7,
    left: -7,
    right: -7,
    bottom: -7,
    borderRadius: 18,
    borderWidth: 1.2,
    borderColor: 'rgba(255,255,255,0.92)',
  },
  cornerDot: {
    position: 'absolute',
    width: 10,
    height: 10,
    borderRadius: borderRadius.full,
    backgroundColor: '#FFFFFF',
  },
  cornerTopLeft: { top: -11, left: -11 },
  cornerTopRight: { top: -11, right: -11 },
  cornerBottomLeft: { bottom: -11, left: -11 },
  cornerBottomRight: { bottom: -11, right: -11 },
  rotationStem: {
    position: 'absolute',
    top: -28,
    left: '50%',
    marginLeft: -1,
    width: 2,
    height: 18,
    backgroundColor: 'rgba(255,255,255,0.82)',
  },
  rotationHandle: {
    position: 'absolute',
    top: -42,
    left: '50%',
    marginLeft: -13,
    width: 26,
    height: 26,
    borderRadius: borderRadius.full,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resizeHandle: {
    position: 'absolute',
    right: -18,
    bottom: -18,
    width: 30,
    height: 30,
    borderRadius: borderRadius.full,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sizeRail: {
    position: 'absolute',
    left: spacing.md,
    top: 174,
    alignItems: 'center',
    gap: spacing.sm,
    zIndex: 5,
  },
  sizeRailLabel: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: typography.fontSize.xs,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  sizeRailTrack: {
    width: 40,
    height: 164,
    borderRadius: 24,
    backgroundColor: 'rgba(6,10,20,0.34)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  sizeRailSlider: {
    width: 160,
    height: 40,
    transform: [{ rotate: '-90deg' }],
  },
  sizeRailValue: {
    color: '#FFFFFF',
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.bold as any,
    minWidth: 28,
    textAlign: 'center',
  },
  contextHintWrap: {
    position: 'absolute',
    left: spacing.xl,
    right: spacing.xl,
    bottom: 86,
    alignItems: 'center',
  },

  floatingModeRail: {
    position: 'absolute',
    left: spacing.lg,
    right: spacing.lg,
    top: spacing.md,
    flexDirection: 'row',
    gap: spacing.sm,
    zIndex: 8,
  },
  floatingModeRailTop: {
    top: spacing.md,
  },
  floatingModeChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: borderRadius.full,
    backgroundColor: 'rgba(7,12,22,0.54)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  floatingModeChipActive: {
    backgroundColor: 'rgba(37,99,235,0.32)',
    borderColor: 'rgba(96,165,250,0.42)',
  },
  floatingModeChipText: {
    color: 'rgba(255,255,255,0.76)',
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold as any,
  },
  floatingModeChipTextActive: {
    color: '#FFFFFF',
  },
  contextHintText: {
    color: 'rgba(255,255,255,0.74)',
    fontSize: typography.fontSize.sm,
    lineHeight: 20,
    textAlign: 'center',
    backgroundColor: 'rgba(5,10,20,0.58)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.full,
    overflow: 'hidden',
  },
  bottomSheet: {
    marginHorizontal: spacing.md,
    marginBottom: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    gap: spacing.md,
    backgroundColor: 'rgba(8,14,26,0.88)',
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    maxHeight: '46%',
  },
  bottomSheetFloating: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: spacing.lg,
    marginHorizontal: 0,
    marginBottom: 0,
    paddingHorizontal: spacing.lg,
    paddingTop: 0,
    paddingBottom: 0,
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderRadius: 0,
  },
  textVariantOverlay: {
    position: 'absolute',
    left: 72,
    right: spacing.lg,
    top: 86,
    gap: spacing.sm,
    backgroundColor: 'rgba(6,10,20,0.24)',
    borderRadius: 20,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  textVariantRail: {
    gap: spacing.sm,
    paddingHorizontal: 2,
    alignItems: 'center',
  },
  textVariantChip: {
    minWidth: 96,
    paddingHorizontal: spacing.lg,
    paddingVertical: 12,
    backgroundColor: 'rgba(10,16,32,0.38)',
    borderColor: 'rgba(255,255,255,0.12)',
  },
  textVariantChipActive: {
    backgroundColor: '#FFFFFF',
    borderColor: '#FFFFFF',
  },
  textVariantChipText: {
    color: '#FFFFFF',
  },
  textVariantChipTextActive: {
    color: '#09111F',
  },
  textActionDock: {
    position: 'absolute',
    left: 72,
    right: spacing.lg,
    bottom: spacing.lg,
    gap: spacing.sm,
    backgroundColor: 'rgba(7,12,22,0.3)',
    borderRadius: 22,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  textColorRail: {
    gap: spacing.sm,
    paddingHorizontal: 2,
    alignItems: 'center',
  },
  textColorChip: {
    width: 32,
    height: 32,
  },
  textToolbarRow: {
    alignSelf: 'stretch',
    justifyContent: 'space-between',
    backgroundColor: 'transparent',
    padding: 0,
    borderWidth: 0,
    borderRadius: 0,
  },
  textToolbarPrimary: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  textToolbarGhost: {
    width: 52,
    minWidth: 52,
    paddingHorizontal: 0,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  textToolbarGhostActive: {
    backgroundColor: 'rgba(59,130,246,0.34)',
    borderWidth: 1,
    borderColor: 'rgba(147,197,253,0.7)',
  },
  textFontRail: {
    gap: spacing.sm,
    paddingHorizontal: 2,
    alignItems: 'center',
  },
  textFontChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: 9,
    borderRadius: borderRadius.full,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  textFontChipActive: {
    backgroundColor: '#FFFFFF',
    borderColor: '#FFFFFF',
  },
  textFontChipText: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.semibold as any,
  },
  textFontChipTextActive: {
    color: '#09111F',
  },
  textProPanel: {
    marginTop: spacing.xs,
    gap: spacing.sm,
    paddingHorizontal: spacing.xs,
    paddingBottom: spacing.xs,
    maxHeight: 230,
  },
  textMiniSlider: {
    borderRadius: 14,
    paddingHorizontal: spacing.sm,
    paddingTop: 8,
    paddingBottom: 4,
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  textMiniSliderHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  textMiniSliderLabel: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.semibold as any,
  },
  textMiniSliderValue: {
    color: 'rgba(255,255,255,0.58)',
    fontSize: typography.fontSize.xs,
  },
  modeRail: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  modeChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 11,
    borderRadius: borderRadius.full,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  modeChipActive: {
    backgroundColor: 'rgba(37,99,235,0.22)',
    borderColor: 'rgba(96,165,250,0.26)',
  },
  modeChipText: {
    color: 'rgba(255,255,255,0.74)',
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold as any,
  },
  modeChipTextActive: {
    color: '#FFFFFF',
  },
  variantRail: {
    gap: spacing.sm,
  },
  variantChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: borderRadius.full,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  variantChipActive: {
    backgroundColor: '#FFFFFF',
    borderColor: '#FFFFFF',
  },
  variantChipText: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold as any,
  },
  variantChipTextActive: {
    color: '#09111F',
  },
  colorRail: {
    gap: spacing.sm,
  },
  colorChip: {
    width: 34,
    height: 34,
    borderRadius: borderRadius.full,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.16)',
  },
  colorChipActive: {
    borderColor: '#FFFFFF',
    transform: [{ scale: 1.06 }],
  },
  toolbarRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  toolbarButtonPrimary: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 13,
    borderRadius: borderRadius.full,
    backgroundColor: '#2563EB',
  },
  toolbarButtonPrimaryText: {
    color: '#FFFFFF',
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.bold as any,
  },
  toolbarButtonGhost: {
    minWidth: 70,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 13,
    borderRadius: borderRadius.full,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  toolbarButtonGhostText: {
    color: '#FFFFFF',
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold as any,
  },
  toolbarButtonDisabled: {
    opacity: 0.4,
  },
  presetRail: {
    gap: spacing.md,
  },
  presetCard: {
    width: 148,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    padding: spacing.md,
  },
  presetCardActive: {
    backgroundColor: 'rgba(37,99,235,0.16)',
    borderColor: 'rgba(96,165,250,0.28)',
  },
  presetSwatch: {
    height: 72,
    borderRadius: 18,
    overflow: 'hidden',
    marginBottom: spacing.sm,
  },
  presetSwatchBlend: {
    flex: 1,
    opacity: 0.72,
  },
  presetCardTitle: {
    color: '#FFFFFF',
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.bold as any,
  },
  presetCardMeta: {
    marginTop: 4,
    color: 'rgba(255,255,255,0.54)',
    fontSize: typography.fontSize.xs,
  },
  presetStrengthWrap: {
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
  },
  gradePanelContent: {
    gap: spacing.md,
    paddingBottom: spacing.md,
  },
  gradeRow: {
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.04)',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
  },
  inspectorHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  inspectorLabel: {
    color: '#FFFFFF',
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold as any,
  },
  inspectorValue: {
    color: 'rgba(255,255,255,0.54)',
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.semibold as any,
  },
  resetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 13,
    borderRadius: borderRadius.full,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  resetButtonText: {
    color: '#DDEAFE',
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold as any,
  },
  composerBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(2,6,16,0.18)',
  },
  composerCanvasTapArea: {
    ...StyleSheet.absoluteFillObject,
  },
  composerTopRow: {
    position: 'absolute',
    top: spacing.lg,
    left: spacing.md,
    right: spacing.md,
    zIndex: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  composerTopBtn: {
    width: 42,
    height: 42,
    borderRadius: borderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(8,15,28,0.54)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  composerTopDone: {
    minWidth: 90,
    height: 42,
    borderRadius: borderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    backgroundColor: '#2563EB',
  },
  composerTopDoneText: {
    color: '#FFFFFF',
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.bold as any,
  },
  composerDraftLayer: {
    position: 'absolute',
    zIndex: 2,
  },
  composerDraftSurface: {
    minHeight: 72,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'visible',
  },
  composerDraftOutline: {
    position: 'absolute',
    top: -7,
    left: -7,
    right: -7,
    bottom: -7,
    borderRadius: 18,
    borderWidth: 1.1,
    borderColor: 'rgba(255,255,255,0.78)',
  },
  composerPreviewSurfaceSunset: {
    backgroundColor: 'rgba(248,113,113,0.34)',
    borderColor: 'rgba(254,215,170,0.52)',
    borderWidth: 1,
  },
  composerPreviewText: {
    width: '100%',
    fontWeight: '900',
    textAlign: 'center',
    textShadowColor: 'rgba(0,0,0,0.52)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 14,
  },
  composerPreviewInput: {
    paddingHorizontal: 0,
    paddingVertical: 0,
    margin: 0,
    minHeight: 52,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  composerPreviewPlaceholder: {
    color: 'rgba(255,255,255,0.52)',
  },
  composerKeyboardWrap: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    zIndex: 4,
    gap: spacing.sm,
  },
  composerChoiceRail: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: 8,
    paddingVertical: 5,
    minHeight: 60,
  },
  composerChoiceChip: {
    minWidth: 88,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(8,15,28,0.76)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  composerChoiceChipActive: {
    backgroundColor: '#FFFFFF',
    borderColor: '#FFFFFF',
  },
  composerChoiceText: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold as any,
  },
  composerChoiceTextActive: {
    color: '#0B1220',
  },
  composerColorChip: {
    width: 42,
    height: 42,
    borderRadius: borderRadius.full,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  composerColorChipActive: {
    borderColor: '#FFFFFF',
    transform: [{ scale: 1.3 }],
    shadowColor: '#FFFFFF',
    shadowOpacity: 0.28,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 0 },
    elevation: 6,
  },
  composerToolBar: {
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'space-between',
    gap: spacing.xs,
    backgroundColor: 'rgba(8,15,28,0.84)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 22,
    paddingHorizontal: spacing.xs,
    paddingVertical: 9,
  },
  composerToolBtn: {
    flex: 1,
    minWidth: 50,
    height: 50,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.04)',
    gap: 2,
    paddingHorizontal: 2,
  },
  composerToolBtnActive: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.92)',
  },
  composerToolText: {
    color: '#FFFFFF',
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.bold as any,
  },
  composerToolTextActive: {
    color: '#08111F',
  },
  composerToolLabel: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 10,
    fontWeight: typography.fontWeight.semibold as any,
    letterSpacing: 0.2,
  },
  composerToolLabelActive: {
    color: '#08111F',
  },
  composerInput: {
    minHeight: 86,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.05)',
    color: '#FFFFFF',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    textAlignVertical: 'top',
    fontSize: typography.fontSize.base,
  },
  composerFooter: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  visualLayerWrap: {
    position: 'absolute',
  },
  visualLayerSurface: {
    width: '100%',
    height: '100%',
  },
  visualLayerSurfaceSelected: {
    transform: [{ scale: 1 }],
  },
  visualLayerShadow: {
    flex: 1,
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOpacity: 0.26,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  visualLayerImage: {
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(255,255,255,0.03)',
  },
  gradeSheet: {
    position: 'absolute',
    left: spacing.sm,
    right: spacing.sm,
    bottom: 112,
    maxHeight: '48%',
    borderRadius: 28,
    backgroundColor: 'rgba(8,14,26,0.94)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    paddingTop: spacing.md,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.md,
    zIndex: 6,
  },
  gradeSheetHeader: {
    marginBottom: spacing.md,
  },
  gradeSheetTitle: {
    color: '#FFFFFF',
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.bold as any,
  },
  gradeSheetSubtitle: {
    marginTop: 4,
    color: 'rgba(255,255,255,0.56)',
    fontSize: typography.fontSize.xs,
  },
  gradeSheetScroll: {
    gap: spacing.md,
    paddingBottom: spacing.xs,
  },
  selectionDock: {
    position: 'absolute',
    left: spacing.sm,
    right: spacing.sm,
    bottom: 112,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    zIndex: 7,
  },
  selectionPrimaryBtn: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(8,15,28,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
  },
  selectionPrimaryBtnText: {
    color: '#FFFFFF',
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold as any,
  },
  selectionPillLabel: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(8,15,28,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
  },
  selectionPillText: {
    color: '#FFFFFF',
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold as any,
  },
  selectionIconBtn: {
    width: 52,
    height: 52,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(8,15,28,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
  },
  selectionIconBtnDanger: {
    borderColor: 'rgba(255,180,180,0.22)',
  },
  actionRail: {
    position: 'absolute',
    left: spacing.sm,
    right: spacing.sm,
    bottom: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    borderRadius: 24,
    backgroundColor: 'rgba(8,15,28,0.86)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    zIndex: 8,
  },
  actionChip: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderRadius: 18,
    paddingVertical: 9,
    paddingHorizontal: 6,
    backgroundColor: 'rgba(255,255,255,0.03)',
  },
  actionChipActive: {
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  actionChipIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  actionChipIconWrapActive: {
    backgroundColor: '#FFFFFF',
  },
  actionChipText: {
    color: 'rgba(255,255,255,0.76)',
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.semibold as any,
  },
  actionChipTextActive: {
    color: '#FFFFFF',
  },
  assetPickerBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(2,6,16,0.42)',
  },
  assetPickerSheet: {
    maxHeight: '78%',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: '#08111F',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.lg,
    borderTopWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  assetPickerHandle: {
    alignSelf: 'center',
    width: 48,
    height: 5,
    borderRadius: borderRadius.full,
    backgroundColor: 'rgba(255,255,255,0.16)',
    marginBottom: spacing.md,
  },
  assetPickerHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  assetPickerTitleWrap: {
    flex: 1,
  },
  assetPickerTitle: {
    color: '#FFFFFF',
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold as any,
  },
  assetPickerSubtitle: {
    marginTop: 4,
    color: 'rgba(255,255,255,0.55)',
    fontSize: typography.fontSize.xs,
    lineHeight: 18,
  },
  assetPickerClose: {
    width: 40,
    height: 40,
    borderRadius: borderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  assetModeRail: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  assetModeChip: {
    flex: 1,
    minHeight: 46,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  assetModeChipActive: {
    backgroundColor: '#FFFFFF',
    borderColor: '#FFFFFF',
  },
  assetModeChipText: {
    color: '#FFFFFF',
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold as any,
  },
  assetModeChipTextActive: {
    color: '#08111F',
  },
  assetSearchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    minHeight: 48,
    borderRadius: 16,
    paddingHorizontal: spacing.md,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    marginBottom: spacing.md,
  },
  assetSearchInput: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: typography.fontSize.sm,
  },
  assetGridContent: {
    paddingBottom: spacing.xl,
    gap: spacing.sm,
  },
  assetGridRow: {
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  assetTile: {
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    overflow: 'hidden',
    marginBottom: spacing.sm,
  },
  assetTileImage: {
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(255,255,255,0.03)',
  },
  assetTileBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: borderRadius.full,
    backgroundColor: 'rgba(8,15,28,0.72)',
  },
  assetTileBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: typography.fontWeight.bold as any,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  assetLoadingWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xl,
    gap: spacing.sm,
  },
  assetEmptyWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xl,
  },
  assetEmptyText: {
    color: 'rgba(255,255,255,0.55)',
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
  },
});