import { StyleSheet } from 'react-native';
import { colors, spacing, typography, borderRadius } from '../../styles/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: '#FFFFFF',  },
  headerContainer: {
    backgroundColor: '#000000',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  headerSide: {
    width: 124,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerButton: {
    marginLeft: 16,
  },
  notificationIconContainer: {
    position: 'relative',
  },
  notificationBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FF3B30',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  notificationBadgeText: {
    color: '#FFFFFF',    fontSize: 10,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  momentsSection: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  momentsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  storiesList: {
    paddingHorizontal: 16,
  },
  storyItem: {
    alignItems: 'center',
    marginRight: 16,
    width: 80,
  },
  createStoryRing: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: '#333333',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#007AFF',
  },
  createStoryContainer: {
    width: 76,
    height: 76,
    borderRadius: 38,
    position: 'relative',
    overflow: 'hidden',
  },
  createStoryAvatar: {
    width: 76,
    height: 76,
    borderRadius: 38,
  },
  createStoryButton: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#007AFF',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  storyUsername: {
    marginTop: 8,
    fontSize: 12,
    color: '#FFFFFF',    textAlign: 'center',
    maxWidth: 80,
  },
  peopleSection: {
    paddingTop: 18,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  peopleSectionHeader: {
    paddingHorizontal: 16,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  peopleSectionTitleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  peopleSectionIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(96, 165, 250, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.24)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  peopleSectionTextWrap: {
    flex: 1,
  },
  peopleSectionTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  peopleSectionSubtitle: {
    color: 'rgba(226, 232, 240, 0.72)',
    fontSize: 12,
    marginTop: 2,
  },
  peopleSectionLink: {
    color: '#93C5FD',
    fontSize: 13,
    fontWeight: '600',
  },
  peopleList: {
    paddingHorizontal: 16,
  },
  peopleCard: {
    width: 188,
    marginRight: 12,
    borderRadius: 22,
    padding: 14,
    backgroundColor: 'rgba(10, 18, 38, 0.88)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.14)',
  },
  peopleCardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  peopleAvatarWrap: {
    padding: 2,
    borderRadius: 32,
    backgroundColor: 'rgba(96, 165, 250, 0.12)',
  },
  peopleFollowButton: {
    minWidth: 80,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#2563EB',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  peopleConnectButton: {
    backgroundColor: '#0F766E',
  },
  peopleRequestButton: {
    backgroundColor: '#374151',
  },
  peopleFollowButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  peopleNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  peopleName: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    maxWidth: 124,
    marginRight: 6,
  },
  peopleUsername: {
    color: 'rgba(226, 232, 240, 0.72)',
    fontSize: 12,
    marginBottom: 10,
  },
  peopleMetaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    maxWidth: '100%',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(15, 23, 42, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.14)',
  },
  peopleMetaPillText: {
    color: '#DBEAFE',
    fontSize: 11,
    marginLeft: 6,
    maxWidth: 126,
  },
  peopleChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
  },
  peopleInterestChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(30, 41, 59, 0.94)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.16)',
    marginRight: 8,
    marginBottom: 8,
  },
  peopleInterestChipText: {
    color: '#E2E8F0',
    fontSize: 11,
    fontWeight: '600',
  },
  peopleActivityText: {
    color: 'rgba(226, 232, 240, 0.62)',
    fontSize: 11,
    marginTop: 2,
  },
  peopleSkeletonRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
  },
  peopleSkeletonCard: {
    width: 188,
    marginRight: 12,
    borderRadius: 22,
    padding: 14,
    backgroundColor: 'rgba(10, 18, 38, 0.78)',
  },
  feedContainer: {
    paddingBottom: 100,
  },
});