import React from 'react';
import { createSettingsScreen } from '../templates/SettingsTemplate';

export default createSettingsScreen({
  title: 'Captions',
  sections: [
    {
      title: 'Display',
      items: [
        { label: 'Always Show Captions', type: 'toggle', icon: 'text', value: false, settingKey: 'alwaysShowCaptions', settingScope: 'settings' },
        { label: 'Auto-Generated Captions', type: 'toggle', icon: 'sparkles', value: true, settingKey: 'autoGeneratedCaptions', settingScope: 'settings' },
      ],
    },
    {
      title: 'Appearance',
      items: [
        { label: 'Caption Size', type: 'navigation', icon: 'resize', navigateTo: 'FontSize' },
        { label: 'Caption Style', type: 'navigation', icon: 'color-palette', navigateTo: 'AppearanceSettings', badge: 'Coming soon', disabled: true },
      ],
    },
  ],
});


