import { Platform, StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000000' },
  backdropLayer: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  ambientOrb: {
    position: 'absolute',
    borderRadius: 999,
    opacity: 0.92,
  },
  ambientOrbPrimary: {
    width: 320,
    height: 320,
    top: -84,
    right: -72,
  },
  ambientOrbSecondary: {
    width: 260,
    height: 260,
    left: -108,
    bottom: 148,
    backgroundColor: 'rgba(125, 211, 252, 0.14)',
  },
  ambientFadeTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 210,
  },
  ambientFadeBottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 260,
  },
  headerBlur: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    paddingTop: Platform.OS === 'ios' ? 44 : 0,
    borderBottomWidth: 1,
  },
  mentionAutocompleteWrap: {
    alignSelf: 'center',
    width: '100%',
    paddingHorizontal: 16,
    marginBottom: 8,
    zIndex: 12,
  },
  composerBlur: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.08)',
    paddingBottom: Platform.OS === 'ios' ? 2 : 0,
    backgroundColor: 'transparent',
  },
  groupRemovalBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 8,
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(248, 113, 113, 0.24)',
    backgroundColor: 'rgba(15, 23, 42, 0.74)',
  },
  groupRemovalMeta: {
    flex: 1,
    minWidth: 0,
  },
  groupRemovalLabel: {
    color: '#fca5a5',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.6,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  groupRemovalText: {
    color: '#e2e8f0',
    fontSize: 13,
    lineHeight: 18,
  },
  groupRemovalActorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
  },
  groupRemovalActor: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  connectingBanner: {
    marginTop: 8,
    marginBottom: 4,
    minHeight: 30,
    borderRadius: 12,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(51, 65, 85, 0.34)',
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.36)',
  },
  connectingBannerText: {
    marginLeft: 8,
    color: '#f8fafc',
    fontSize: 12,
    fontWeight: '700',
  },
  typingIndicatorContainer: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 20,
    position: 'absolute',
    bottom: 96,
    left: 18,
    zIndex: 5,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    overflow: 'hidden',
  },
  typingIndicatorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 154,
  },
  typingIndicatorAvatar: {
    marginRight: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
  },
  typingIndicatorMeta: {
    flex: 1,
    minWidth: 0,
  },
  typingIndicatorName: {
    color: '#f8fafc',
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 3,
  },
  typingIndicatorDotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  typingIndicatorDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    marginRight: 4,
    backgroundColor: 'rgba(148, 163, 184, 0.8)',
  },
  typingIndicatorDotPrimary: {
    backgroundColor: '#38bdf8',
  },
  typingIndicatorText: {
    color: '#38bdf8',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.2,
    marginLeft: 3,
  },
  messageListStage: {
    flex: 1,
    paddingTop: Platform.OS === 'ios' ? 90 : 76,
  },
  contentFrame: {
    width: '100%',
    alignSelf: 'center',
  },
  pinnedBannerFrame: {
    alignSelf: 'center',
    marginTop: Platform.OS === 'ios' ? 78 : 68,
    marginBottom: 6,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 12,
  },
  backButton: { padding: 8, marginRight: 12 },
  headerUser: { flex: 1, flexDirection: 'row', alignItems: 'center' },
  headerAvatar: { width: 44, height: 44, borderRadius: 22, marginRight: 12 },
  headerInfo: { flex: 1 },
  headerNameRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'nowrap' },
  headerName: { fontSize: 16, fontWeight: '700', color: '#f3f7ff', flexShrink: 1, letterSpacing: 0.2 },
  headerSub: { fontSize: 11, color: '#9fb0c7', marginTop: 2 },
  typingIndicator: { fontSize: 12, color: '#38bdf8', marginTop: 2 },
  onlineStatus: { fontSize: 12, color: '#22c55e', marginTop: 2 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  headerButton: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(15, 23, 42, 0.45)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  requestBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#312e81',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 8,
  },
  requestText: { flex: 1, fontSize: 13, color: '#cbd5e1' },
  messagesList: { padding: 16 },
  olderMessagesLoader: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(7, 14, 28, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.14)',
  },
  olderMessagesLoaderText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#cbd5e1',
  },
  dayTimeSeparatorWrap: {
    alignSelf: 'center',
    marginVertical: 6,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.22)',
    backgroundColor: 'rgba(2, 6, 23, 0.48)',
  },
  dayTimeSeparatorText: {
    fontSize: 11,
    color: '#cbd5e1',
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  messageRow: { flexDirection: 'row', marginBottom: 10, alignItems: 'flex-end', width: '100%', overflow: 'visible' },
  messageRowMe: { justifyContent: 'flex-end' },
  messageRowSwipeContent: { flexDirection: 'row', alignItems: 'flex-end', width: '100%' },
  messageRowSwipeContentMe: { justifyContent: 'flex-end' },
  messageAvatarSlot: { width: 42, alignItems: 'flex-start', justifyContent: 'flex-end' },
  messageAvatar: { width: 34, height: 34, borderRadius: 17, marginRight: 8, marginBottom: 2 },
  messageBubbleWrap: { flex: 1, width: '100%', alignItems: 'flex-start', minWidth: 0, overflow: 'visible' },
  messageBubbleWrapMe: { alignItems: 'flex-end', paddingRight: 2 },
  messageBubble: { maxWidth: '78%', minWidth: 0, borderRadius: 28, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 12, alignSelf: 'flex-start', flexShrink: 1, borderWidth: 1, borderColor: 'rgba(148, 163, 184, 0.16)', shadowColor: '#020617', shadowOpacity: 0.28, shadowRadius: 22, shadowOffset: { width: 0, height: 10 }, elevation: 6 },
  messageBubbleTimed: { paddingBottom: 32 },
  messageBubbleWithReply: { minWidth: 0 },
  messageBubbleCompact: { minWidth: 88 },
  messageBubbleBare: { backgroundColor: 'transparent', paddingHorizontal: 0, paddingVertical: 0, borderRadius: 0, maxWidth: '100%', shadowOpacity: 0, shadowRadius: 0, shadowOffset: { width: 0, height: 0 }, elevation: 0, position: 'relative' },
  messageBubbleMe: { backgroundColor: '#34D399', alignSelf: 'flex-end', borderColor: 'rgba(255, 255, 255, 0.28)' },
  messageBubbleOther: { backgroundColor: '#1C2740', borderColor: 'rgba(148, 163, 184, 0.22)' },
  messageBubbleMeCard: { backgroundColor: 'rgba(52, 211, 153, 0.12)', borderColor: 'rgba(52, 211, 153, 0.46)', shadowColor: '#020617', shadowOpacity: 0.2, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 3 },
  messageBubbleOtherCard: { backgroundColor: '#111c31', borderColor: 'rgba(148, 163, 184, 0.22)', shadowColor: '#020617', shadowOpacity: 0.16, shadowRadius: 14, shadowOffset: { width: 0, height: 8 }, elevation: 3 },
  latestHighlight: { shadowColor: '#38bdf8', shadowOpacity: 0.28, shadowRadius: 14, shadowOffset: { width: 0, height: 6 } },
  replyPreview: { marginBottom: 10, backgroundColor: 'transparent', borderRadius: 0, paddingVertical: 0, paddingHorizontal: 0, paddingLeft: 0, minWidth: 0, alignSelf: 'stretch', borderWidth: 0, borderLeftWidth: 0 },
  replyHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 },
  replyContextLabel: { fontSize: 12, fontWeight: '700', color: 'rgba(226, 232, 240, 0.78)', marginBottom: 0, lineHeight: 16 },
  replyUsername: { fontSize: 12, fontWeight: '700', color: '#38bdf8', flex: 1 },
  replyType: { fontSize: 10, color: '#94a3b8', textTransform: 'uppercase' },
  replyBody: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, width: '100%' },
  replySnippet: { flexDirection: 'row', alignItems: 'center', gap: 8, width: '100%', backgroundColor: 'rgba(2, 6, 23, 0.22)', borderRadius: 16, paddingHorizontal: 10, paddingVertical: 8, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  replyThumb: { width: 28, height: 28, borderRadius: 8, backgroundColor: '#0F172A' },
  replyTextWrap: { flex: 1, minWidth: 0, flexGrow: 1, flexShrink: 1 },
  replyText: { fontSize: 13, color: 'rgba(241, 245, 249, 0.86)', lineHeight: 18, flexShrink: 1 },
  replyMore: { fontSize: 11, color: '#38bdf8', fontWeight: '700', marginTop: 4 },
  messageText: { fontSize: 15, lineHeight: 22, color: '#e2e8f0', flexShrink: 1, flexWrap: 'wrap', minWidth: 0, maxWidth: '100%', paddingRight: 0, paddingTop: 0, paddingBottom: 0, includeFontPadding: false, alignSelf: 'flex-start' },
  messageTextMe: { color: '#e2e8f0' },
  messageTextDeleted: { color: '#cbd5e1', fontStyle: 'italic' },
  messageFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', width: '100%', marginTop: 6, gap: 4, minHeight: 14 },
  messageFooterTimed: { position: 'absolute', right: 14, bottom: 10, width: 'auto', marginTop: 0, minHeight: 0, gap: 3 },
  messageFooterOverlay: { position: 'absolute', right: 6, bottom: 6, backgroundColor: 'rgba(2, 6, 23, 0.68)', paddingHorizontal: 7, paddingVertical: 3, borderRadius: 10 },
  messageFooterMedia: { marginTop: 6, paddingHorizontal: 4 },
  messageFooterMe: { justifyContent: 'flex-end' },
  swipeAction: { width: 112, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 6 },
  swipeActionLeft: { backgroundColor: 'transparent', borderTopLeftRadius: 12, borderBottomLeftRadius: 12, alignItems: 'flex-start' },
  swipeActionRight: { backgroundColor: 'transparent', borderTopRightRadius: 12, borderBottomRightRadius: 12, alignItems: 'flex-end' },
  swipeActionText: { fontSize: 10, color: '#38bdf8', fontWeight: '700', marginTop: 4 },
  swipeActionHint: { fontSize: 10, color: '#e2e8f0', marginTop: 2, fontWeight: '600' },
  messageTime: { fontSize: 11, color: '#94a3b8', flexShrink: 0 },
  messageTimeMe: { color: '#cbd5e1', textAlign: 'right' },
  threadTimelineTime: {
    position: 'absolute',
    right: 2,
    bottom: 8,
    minWidth: 62,
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'right',
    color: 'rgba(203, 213, 225, 0.94)',
  },
  threadTimelineTimeMe: {
    color: 'rgba(224, 231, 255, 0.96)',
    right: 1,
  },
  threadTimelineTimeOther: {
    color: 'rgba(191, 219, 254, 0.88)',
  },
  readIcon: { marginLeft: 2 },
  seenLabel: { marginTop: 6, marginRight: 12, textAlign: 'right', alignSelf: 'flex-end' },
  seenLabelFresh: { fontSize: 11, color: 'rgba(255,255,255,0.98)', fontWeight: '500' },
  seenLabelAged: { fontSize: 10, color: 'rgba(203,213,225,0.66)', fontWeight: '400' },
  replyContainer: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 11, backgroundColor: '#111827', borderWidth: 1, borderColor: '#1f2937', borderRadius: 18, marginHorizontal: 12, marginBottom: 8 },
  replyContent: { flex: 1 },
  replyLabel: { fontSize: 12, fontWeight: '600', color: '#38bdf8', marginBottom: 2 },
  replyBarType: { fontSize: 11, color: '#94a3b8', marginBottom: 4 },
  replyBarMore: { fontSize: 11, color: '#38bdf8', fontWeight: '700', marginTop: 4 },
  inputContainer: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingTop: 8, paddingBottom: 10, marginBottom: 2, backgroundColor: 'transparent' },
  inputButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#111827', borderWidth: 1, borderColor: '#1f2937', alignItems: 'center', justifyContent: 'center' },
  textInputContainer: { flex: 1, flexDirection: 'row', alignItems: 'center', backgroundColor: '#10192D', borderRadius: 34, paddingLeft: 12, paddingRight: 12, paddingVertical: 6, borderWidth: 1, borderColor: '#22314F', minHeight: 58, maxHeight: 148, gap: 10, position: 'relative' },
  textInputContainerTyping: { paddingLeft: 12 },
  leadingIconButton: { width: 48, height: 48, borderRadius: 24, borderWidth: 1, borderColor: '#24324f', alignItems: 'center', justifyContent: 'center' },
  textInput: { flex: 1, minWidth: 0, fontSize: 18, color: '#e2e8f0', lineHeight: 24, maxHeight: 118, paddingTop: Platform.OS === 'android' ? 6 : 4, paddingBottom: Platform.OS === 'android' ? 6 : 4, paddingHorizontal: 2, includeFontPadding: true, textAlignVertical: 'top' },
  inputActionsDock: { width: 116, marginLeft: 8, alignSelf: 'stretch', justifyContent: 'center', flexShrink: 0 },
  inputActionsRow: { ...StyleSheet.absoluteFillObject, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 8 },
  miniActionButton: { width: 48, height: 48, borderRadius: 24, borderWidth: 1, borderColor: '#24324f', alignItems: 'center', justifyContent: 'center' },
  inputSendRow: { ...StyleSheet.absoluteFillObject, alignItems: 'flex-end', justifyContent: 'center' },
  emojiIcon: { width: 30, height: 30, tintColor: '#94a3b8' },
  sendButton: { width: 52, height: 52, borderRadius: 26, backgroundColor: '#38bdf8', justifyContent: 'center', alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 4, shadowOffset: { width: 0, height: 2 }, elevation: 3 },
  sendButtonDisabled: { opacity: 0.5 },
  reactionBadge: {
    shadowOffset: { width: 0, height: 4 },
    position: 'absolute',
    bottom: -10,
    backgroundColor: '#0F172A',
    borderRadius: 12,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: '#1f2937',
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 4,
  },
  reactionBadgeRight: {
    right: 8,
  },
  reactionBadgeLeft: {
    left: 8,
  },
  reactionText: { fontSize: 13, color: '#e2e8f0' },
  mediaPlaceholder: { width: 240, height: 260, borderRadius: 16, backgroundColor: 'rgba(15, 23, 42, 0.66)', justifyContent: 'center', alignItems: 'center', marginBottom: 8, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  mediaBare: { alignSelf: 'flex-start' },
  messageImage: { width: 240, height: 260, borderRadius: 16, marginBottom: 8 },
  messageImageBare: { width: 260, height: 260, borderRadius: 0, marginBottom: 0, backgroundColor: 'transparent' },
  messageVideo: { width: 240, height: 280, borderRadius: 16, marginBottom: 8, backgroundColor: '#000' },
  mediaTag: { fontSize: 11, color: '#94a3b8', marginTop: 2 },
  qrOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.35)', justifyContent: 'center', alignItems: 'center' },
  qrSheet: { width: '88%', backgroundColor: '#0F172A', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: '#1f2937' },
  qrTitle: { fontSize: 16, fontWeight: '600', marginBottom: 6, color: '#e2e8f0' },
  qrHint: { fontSize: 11, color: '#94a3b8', marginBottom: 10, lineHeight: 16 },
  qrRow: { flexDirection: 'row', justifyContent: 'flex-start', flexWrap: 'wrap', gap: 8 },
  qrEmojiBtn: { minWidth: 54, height: 54, paddingHorizontal: 10, alignItems: 'center', justifyContent: 'center', borderRadius: 14, backgroundColor: '#111827' },
  qrEmojiSelected: { backgroundColor: '#1e3a8a', borderWidth: 1, borderColor: '#6ee7ff', transform: [{ scale: 1.08 }] },
  qrEmoji: { fontSize: 22, color: '#e2e8f0' },
  moreReactSheet: { width: '90%', backgroundColor: '#0F172A', borderRadius: 18, padding: 16, borderWidth: 1, borderColor: '#1f2937' },
  moreReactGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 10 },
  moreReactItem: { width: '16%', height: 54, alignItems: 'center', justifyContent: 'center', borderRadius: 14, backgroundColor: '#111827' },
  moreReactEmoji: { fontSize: 22, color: '#e2e8f0' },
  actionOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.26)' },
  reactionsListBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.42)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 18,
  },
  reactionsListModal: {
    width: '100%',
    maxWidth: 420,
    maxHeight: '64%',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#1f2937',
    backgroundColor: '#0F172A',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  reactionsListHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  reactionsListTitle: {
    color: '#e2e8f0',
    fontSize: 16,
    fontWeight: '700',
  },
  reactionsListContent: {
    paddingBottom: 4,
  },
  reactionsListEmpty: {
    color: '#94a3b8',
    fontSize: 13,
    paddingVertical: 12,
    textAlign: 'center',
  },
  reactionUserRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  reactionUserMeta: {
    flex: 1,
    marginLeft: 10,
    marginRight: 10,
  },
  reactionUserName: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '600',
  },
  reactionUserHandle: {
    color: '#94a3b8',
    fontSize: 12,
    marginTop: 1,
  },
  reactionUserEmoji: {
    fontSize: 22,
  },
  actionSheet: {
    backgroundColor: '#0F172A',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#1f2937',
    marginHorizontal: 12,
    marginBottom: 18,
  },
  actionSheetPopover: { position: 'absolute', marginHorizontal: 0, marginBottom: 0, shadowColor: '#000', shadowOpacity: 0.28, shadowRadius: 18, shadowOffset: { width: 0, height: 10 }, elevation: 12 },
  actionRow: { paddingVertical: 9 },
  actionRowInner: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  actionLabel: { fontSize: 14, color: '#e2e8f0' },
  actionLabelDanger: { color: '#f87171' },
  reactionBar: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: 8,
    gap: 8,
  },
  reactionChip: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#0F172A',
    borderWidth: 1,
    borderColor: '#1f2937',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reactionChipPlus: { width: 46, height: 46, borderRadius: 23, backgroundColor: 'rgba(56, 189, 248, 0.14)', borderColor: '#38bdf8' },
  reactionChipActive: {
    backgroundColor: 'rgba(56, 189, 248, 0.18)',
    borderColor: '#38bdf8',
  },
  reactionChipText: {
    fontSize: 18,
    color: '#e2e8f0',
  },
  pinnedBanner: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 13, backgroundColor: 'rgba(30, 41, 59, 0.65)', borderWidth: 1, borderColor: 'rgba(56, 189, 248, 0.18)', borderRadius: 18, overflow: 'hidden' },
  pinnedIconWrap: { width: 32, height: 32, borderRadius: 16, backgroundColor: 'rgba(56, 189, 248, 0.18)', alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  pinnedLabel: { fontSize: 12, color: '#38bdf8' },
  pinnedPreview: { fontSize: 13, color: '#e2e8f0' },
  pinnedCounter: { fontSize: 12, color: '#38bdf8', marginLeft: 8 },
  pinBadge: { position: 'absolute', top: -10, right: -6, backgroundColor: '#1e293b', borderRadius: 12, padding: 4 },
  pollBubbleWide: { width: '86%', maxWidth: 420, minWidth: 0 },
  pollCard: { backgroundColor: '#0F172A', borderRadius: 18, padding: 12, gap: 10, borderWidth: 1, borderColor: '#1f2937' },
  pollHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  pollQuestion: { color: '#e2e8f0', fontSize: 16, fontWeight: '700', flex: 1 },
  pollVotedTag: { color: '#38bdf8', fontSize: 11, fontWeight: '700', textTransform: 'uppercase' },
  pollOption: { backgroundColor: '#111827', borderRadius: 12, paddingVertical: 10, paddingHorizontal: 12, marginTop: 6, overflow: 'hidden', minHeight: 56 },
  pollOptionSelected: { borderWidth: 1, borderColor: '#38bdf8', backgroundColor: 'rgba(56, 189, 248, 0.08)' },
  pollBar: { position: 'absolute', left: 0, top: 0, bottom: 0, backgroundColor: '#2563eb', borderRadius: 12, opacity: 0.2 },
  pollBarSelected: { opacity: 0.32 },
  pollOptionContent: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
  pollOptionText: { color: '#e5e7eb', fontSize: 14, flex: 1 },
  pollOptionTextSelected: { color: '#e2e8f0', fontWeight: '700' },
  pollPct: { color: '#cbd5e1', fontSize: 12 },
  pollPctSelected: { color: '#38bdf8', fontWeight: '700' },
  pollVotes: { color: '#94a3b8', fontSize: 11, marginTop: 6 },
  pollFooter: { color: '#94a3b8', fontSize: 12 },
  locCard: { backgroundColor: '#0b1324', borderRadius: 18, padding: 13, borderWidth: 1, borderColor: '#1f2937' },
  locTitle: { fontSize: 15, color: '#e2e8f0', fontWeight: '700' },
  locCoords: { fontSize: 12, color: '#94a3b8', marginTop: 6 },
  locBtn: { alignSelf: 'flex-start', paddingVertical: 8, paddingHorizontal: 12, borderRadius: 10, backgroundColor: '#38bdf8' },
  locBtnText: { color: '#0b1220', fontSize: 12, fontWeight: '700' },
  sharedCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(15, 23, 42, 0.2)', borderRadius: 16, padding: 11, gap: 10, borderWidth: 1, borderColor: 'rgba(148, 163, 184, 0.14)' },
  sharedThumb: { width: 54, height: 54, borderRadius: 12 },
  sharedTitle: { fontSize: 14, color: '#e2e8f0', fontWeight: '600' },
  sharedSubtitle: { fontSize: 12, color: '#cbd5e1' },
  messageBubbleMeMedia: {
    backgroundColor: 'transparent',
  },
  editedLabelWrap: {
    marginTop: 2,
    alignSelf: 'flex-end',
  },
  editedLabel: {
    fontSize: 10,
    color: '#94a3b8',
    fontStyle: 'italic',
  },
  shareSheetDock: { flex: 1, justifyContent: 'flex-end' },
  shareSheet: { backgroundColor: '#0F172A', marginHorizontal: 14, marginBottom: 18, paddingHorizontal: 16, paddingTop: 14, paddingBottom: 12, borderRadius: 22, borderWidth: 1, borderColor: '#1f2937' },
  shareTitle: { color: '#e2e8f0', fontSize: 14, fontWeight: '600', marginBottom: 12 },
  shareRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  shareItem: { width: '31%', alignItems: 'center', paddingVertical: 12, backgroundColor: '#111827', borderRadius: 14, borderWidth: 1, borderColor: 'rgba(56, 189, 248, 0.12)' },
  editingBanner: {
    alignSelf: 'center',
    marginHorizontal: 12,
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: '#0f172a',
    borderWidth: 1,
    borderColor: '#1f2937',
    flexDirection: 'row',
    alignItems: 'center',
  },
  editingBannerText: {
    flex: 1,
  },
  editingBannerLabel: {
    color: '#38bdf8',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 3,
  },
  editingBannerPreview: {
    color: '#cbd5e1',
    fontSize: 13,
  },
  shareLabel: { marginTop: 6, color: '#cbd5e1', fontSize: 12 },
  scrollToBottomButton: {
    position: 'absolute',
    right: 16,
    bottom: 84,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(15,23,42,0.95)',
    borderWidth: 1,
    borderColor: '#1f2937',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
});

export default styles;
