import { StyleSheet } from 'react-native';
import { colors, spacing, typography, borderRadius } from '../../styles/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
  },
  debugBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    zIndex: 9999,
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.2)'
  },
  debugBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
  },
  loadingText: {
    color: 'white',
    marginTop: spacing.md,
    fontSize: typography.fontSize.base,
  },
  progressContainer: {
    position: 'absolute',
    top: 50,
    left: 10,
    right: 10,
    flexDirection: 'row',
    gap: 4,
    zIndex: 10,
  },
  progressBar: {
    flex: 1,
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderRadius: 999,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#F4FDFF',
    borderRadius: 999,
  },
  headerGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 170,
    zIndex: 5,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingTop: 60,
  },
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  userInfoChip: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderRadius: 22,
    paddingVertical: 10,
    paddingHorizontal: 2,
    marginRight: 10,
  },
  avatar: {
    borderWidth: 1.8,
    borderColor: 'rgba(255,255,255,0.46)',
  },
  userDetails: {
    marginLeft: 12,
    flex: 1,
  },
  usernameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  username: {
    color: 'white',
    fontSize: 18,
    fontWeight: typography.fontWeight.bold as any,
    textShadowColor: 'rgba(0,0,0,0.35)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  verifiedBadgeIcon: {
    marginTop: 0,
    marginLeft: 1,
  },
  timestamp: {
    color: 'rgba(236,247,255,0.88)',
    fontSize: 13,
    marginTop: 2,
  },
  musicBadgeText: {
    marginTop: 4,
    color: '#F4F7FF',
    fontSize: 10,
    fontWeight: '600',
    backgroundColor: 'rgba(20,26,54,0.68)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 999,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(11,18,42,0.56)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.34)',
  },
  storyContent: {
    flex: 1,
  },
  storyMedia: {
    flex: 1,
  },
  storyImage: {
    width: '100%',
    height: '100%',
  },
  bottomGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 240,
    justifyContent: 'flex-end',
  },
  bottomActions: {
    paddingHorizontal: 14,
    paddingBottom: 28,
  },
  ownerBottomRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 12,
  },
  ownerAudienceWrap: {
    alignItems: 'flex-start',
    justifyContent: 'center',
    gap: 4,
  },
  viewersIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
    minWidth: 56,
    height: 48,
    justifyContent: 'flex-start',
    paddingHorizontal: 0,
    borderRadius: borderRadius.full,
    alignSelf: 'flex-start',
    gap: 8,
  },
  groupIcon: {
    width: 24,
    height: 24,
    tintColor: 'white',
    opacity: 0.9,
  },
  stackedAvatars: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  stackedAvatarWrap: {
    position: 'relative',
  },
  stackedAvatar: {
    borderWidth: 2,
    borderColor: 'rgba(1,8,20,0.72)',
  },
  stackedAvatarHeart: {
    position: 'absolute',
    right: -2,
    bottom: -2,
  },
  viewersCountPill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 9,
    height: 26,
    borderRadius: 999,
    backgroundColor: 'rgba(7,22,44,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  ownerEmptyIcon: {
    width: 26,
    height: 26,
    tintColor: '#DCE7F5',
    opacity: 0.95,
  },
  seenByText: {
    color: 'rgba(190,199,216,0.82)',
    fontSize: 11,
    marginLeft: 2,
    letterSpacing: 0.2,
  },
  viewersCountText: {
    color: '#E7F3FF',
    fontSize: 11,
    fontWeight: '700',
  },
  ownerActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  ownerAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 0,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.34)',
    width: 44,
    height: 44,
    justifyContent: 'center',
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderRadius: 999,
  },
  ownerActionLabel: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600',
  },
  viewsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.1)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.full,
    marginBottom: spacing.md,
  },
  viewsText: {
    color: 'white',
    fontSize: typography.fontSize.sm,
    marginLeft: spacing.xs,
  },
  emojiContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 10,
  },
  emojiButton: {
    backgroundColor: 'rgba(11,18,42,0.56)',
    borderRadius: borderRadius.full,
    padding: 10,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  emojiText: {
    fontSize: 20,
  },
  sentToastWrap: {
    position: 'absolute',
    alignSelf: 'center',
    bottom: 136,
    backgroundColor: 'rgba(8,14,30,0.82)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    zIndex: 60,
  },
  sentToastText: {
    color: '#EAF4FF',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  replyContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(11,18,42,0.66)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    borderRadius: 999,
    paddingLeft: 14,
    paddingRight: 8,
    paddingVertical: 6,
  },
  replyInput: {
    flex: 1,
    paddingHorizontal: 0,
    paddingVertical: 0,
    color: 'white',
    fontSize: 15,
    marginRight: 8,
  },
  sendButton: {
    backgroundColor: 'rgba(77,208,225,0.24)',
    borderRadius: borderRadius.full,
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(77,208,225,0.72)',
  },
  heartButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shareInlineButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  insightsContainer: {
    flex: 1,
    backgroundColor: '#090F22',
  },
  insightsBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(2,6,20,0.62)',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  insightsSheet: {
    width: '100%',
    maxHeight: '80%',
    backgroundColor: 'rgba(7,13,30,0.96)',
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    overflow: 'hidden',
  },
  insightsHandle: {
    width: 42,
    height: 4,
    borderRadius: 999,
    alignSelf: 'center',
    marginTop: 8,
    marginBottom: 8,
    backgroundColor: 'rgba(255,255,255,0.22)',
  },
  insightsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.sm,
  },
  insightsTitle: {
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold as any,
    color: '#F8FBFF',
    letterSpacing: 0.2,
  },
  insightsSubtitle: {
    marginTop: 3,
    fontSize: typography.fontSize.sm,
    color: 'rgba(220,231,255,0.75)',
  },
  insightsCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  loadingInsights: {
    marginTop: spacing.xl,
  },
  viewersList: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.lg,
    paddingTop: spacing.xs,
  },
  viewerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.045)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.09)',
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  viewerAvatarWrap: {
    position: 'relative',
  },
  viewerInfo: {
    flex: 1,
    marginLeft: spacing.sm,
    marginRight: spacing.sm,
  },
  viewerNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  viewerUsername: {
    fontSize: typography.fontSize.base,
    color: '#F5F9FF',
    fontWeight: typography.fontWeight.semibold as any,
  },
  viewerVerifiedBadge: {
    marginTop: 1,
  },
  viewerDisplayName: {
    marginTop: 2,
    fontSize: typography.fontSize.sm,
    color: 'rgba(209,222,247,0.76)',
  },
  viewerHeartBadge: {
    position: 'absolute',
    right: -2,
    bottom: -2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  moreMenu: {
    backgroundColor: 'rgba(10,14,34,0.94)',
    borderRadius: 18,
    padding: spacing.sm,
    width: '70%',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.md,
  },
  menuText: {
    fontSize: typography.fontSize.base,
    color: colors.text.primary,
    marginLeft: spacing.md,
  },
  deleteDialog: {
    backgroundColor: 'rgba(10,14,34,0.95)',
    borderRadius: 20,
    padding: spacing.lg,
    width: '80%',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  deleteTitle: {
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold as any,
    color: colors.text.primary,
    marginBottom: spacing.sm,
  },
  deleteMessage: {
    fontSize: typography.fontSize.base,
    color: colors.text.secondary,
    marginBottom: spacing.lg,
  },
  deleteActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  cancelButton: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  cancelText: {
    fontSize: typography.fontSize.base,
    color: colors.text.secondary,
  },
  deleteButton: {
    backgroundColor: colors.accent.error,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    marginLeft: spacing.md,
  },
  deleteText: {
    fontSize: typography.fontSize.base,
    color: 'white',
    fontWeight: typography.fontWeight.semibold as any,
  },
  textOverlay: {
    position: 'absolute',
  },
  overlayText: {
    // Base styles for overlay text
  },
  stickerOverlay: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  stickerEmoji: {
    fontSize: 40,
    textShadowColor: 'rgba(0,0,0,0.6)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  stickerLabel: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderColor: 'rgba(0,0,0,0.1)',
    borderWidth: 1,
    borderRadius: 16,
    width: 44,
    height: 44,
    justifyContent: 'center',
    paddingHorizontal: 0,
    paddingVertical: 6,
  },
  stickerLabelText: {
    color: '#000',
    fontWeight: '600',
  },
});